// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: padcli/jetconfig/jetconfig.proto

package jetconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstanceType int32

const (
	InstanceType_UNKNOWN     InstanceType = 0
	InstanceType_NANO        InstanceType = 1
	InstanceType_MICRO       InstanceType = 2
	InstanceType_SMALL       InstanceType = 3
	InstanceType_MEDIUM      InstanceType = 4
	InstanceType_MEDIUM_PLUS InstanceType = 5
)

// Enum value maps for InstanceType.
var (
	InstanceType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NANO",
		2: "MICRO",
		3: "SMALL",
		4: "MEDIUM",
		5: "MEDIUM_PLUS",
	}
	InstanceType_value = map[string]int32{
		"UNKNOWN":     0,
		"NANO":        1,
		"MICRO":       2,
		"SMALL":       3,
		"MEDIUM":      4,
		"MEDIUM_PLUS": 5,
	}
)

func (x InstanceType) Enum() *InstanceType {
	p := new(InstanceType)
	*p = x
	return p
}

func (x InstanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_padcli_jetconfig_jetconfig_proto_enumTypes[0].Descriptor()
}

func (InstanceType) Type() protoreflect.EnumType {
	return &file_padcli_jetconfig_jetconfig_proto_enumTypes[0]
}

func (x InstanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceType.Descriptor instead.
func (InstanceType) EnumDescriptor() ([]byte, []int) {
	return file_padcli_jetconfig_jetconfig_proto_rawDescGZIP(), []int{0}
}

var File_padcli_jetconfig_jetconfig_proto protoreflect.FileDescriptor

var file_padcli_jetconfig_jetconfig_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x61, 0x64, 0x63, 0x6c, 0x69, 0x2f, 0x6a, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2f, 0x6a, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x6a, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2a, 0x58, 0x0a,
	0x0c, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x41,
	0x4e, 0x4f, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x49, 0x43, 0x52, 0x4f, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x45,
	0x44, 0x49, 0x55, 0x4d, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x45, 0x44, 0x49, 0x55, 0x4d,
	0x5f, 0x50, 0x4c, 0x55, 0x53, 0x10, 0x05, 0x42, 0x8d, 0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e,
	0x6a, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x0e, 0x4a, 0x65, 0x74, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x28, 0x67, 0x6f, 0x2e,
	0x6a, 0x65, 0x74, 0x70, 0x61, 0x63, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x70, 0x61, 0x64, 0x2f, 0x70, 0x61, 0x64, 0x63, 0x6c, 0x69, 0x2f, 0x6a, 0x65, 0x74, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0xa2, 0x02, 0x03, 0x4a, 0x58, 0x58, 0xaa, 0x02, 0x09, 0x4a, 0x65,
	0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0xca, 0x02, 0x09, 0x4a, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0xe2, 0x02, 0x15, 0x4a, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x4a, 0x65,
	0x74, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_padcli_jetconfig_jetconfig_proto_rawDescOnce sync.Once
	file_padcli_jetconfig_jetconfig_proto_rawDescData = file_padcli_jetconfig_jetconfig_proto_rawDesc
)

func file_padcli_jetconfig_jetconfig_proto_rawDescGZIP() []byte {
	file_padcli_jetconfig_jetconfig_proto_rawDescOnce.Do(func() {
		file_padcli_jetconfig_jetconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_padcli_jetconfig_jetconfig_proto_rawDescData)
	})
	return file_padcli_jetconfig_jetconfig_proto_rawDescData
}

var file_padcli_jetconfig_jetconfig_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_padcli_jetconfig_jetconfig_proto_goTypes = []interface{}{
	(InstanceType)(0), // 0: jetconfig.InstanceType
}
var file_padcli_jetconfig_jetconfig_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_padcli_jetconfig_jetconfig_proto_init() }
func file_padcli_jetconfig_jetconfig_proto_init() {
	if File_padcli_jetconfig_jetconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_padcli_jetconfig_jetconfig_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_padcli_jetconfig_jetconfig_proto_goTypes,
		DependencyIndexes: file_padcli_jetconfig_jetconfig_proto_depIdxs,
		EnumInfos:         file_padcli_jetconfig_jetconfig_proto_enumTypes,
	}.Build()
	File_padcli_jetconfig_jetconfig_proto = out.File
	file_padcli_jetconfig_jetconfig_proto_rawDesc = nil
	file_padcli_jetconfig_jetconfig_proto_goTypes = nil
	file_padcli_jetconfig_jetconfig_proto_depIdxs = nil
}
