// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/api/env.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment int32

const (
	// NONE ensures Environment is always explicitly sent by the client
	Environment_NONE    Environment = 0
	Environment_DEV     Environment = 1
	Environment_PROD    Environment = 2
	Environment_STAGING Environment = 3
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "NONE",
		1: "DEV",
		2: "PROD",
		3: "STAGING",
	}
	Environment_value = map[string]int32{
		"NONE":    0,
		"DEV":     1,
		"PROD":    2,
		"STAGING": 3,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_env_proto_enumTypes[0].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_proto_api_env_proto_enumTypes[0]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_env_proto_rawDescGZIP(), []int{0}
}

var File_proto_api_env_proto protoreflect.FileDescriptor

var file_proto_api_env_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x76, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x2a, 0x37, 0x0a, 0x0b, 0x45, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x45, 0x56, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x50, 0x52, 0x4f, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x47, 0x49, 0x4e,
	0x47, 0x10, 0x03, 0x42, 0x62, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x42, 0x08,
	0x45, 0x6e, 0x76, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x6f, 0x2e, 0x6a,
	0x65, 0x74, 0x70, 0x61, 0x63, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x70, 0x61, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0xa2, 0x02, 0x03,
	0x41, 0x58, 0x58, 0xaa, 0x02, 0x03, 0x41, 0x70, 0x69, 0xca, 0x02, 0x03, 0x41, 0x70, 0x69, 0xe2,
	0x02, 0x0f, 0x41, 0x70, 0x69, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x03, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_env_proto_rawDescOnce sync.Once
	file_proto_api_env_proto_rawDescData = file_proto_api_env_proto_rawDesc
)

func file_proto_api_env_proto_rawDescGZIP() []byte {
	file_proto_api_env_proto_rawDescOnce.Do(func() {
		file_proto_api_env_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_env_proto_rawDescData)
	})
	return file_proto_api_env_proto_rawDescData
}

var file_proto_api_env_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_env_proto_goTypes = []interface{}{
	(Environment)(0), // 0: api.Environment
}
var file_proto_api_env_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_env_proto_init() }
func file_proto_api_env_proto_init() {
	if File_proto_api_env_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_env_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_env_proto_goTypes,
		DependencyIndexes: file_proto_api_env_proto_depIdxs,
		EnumInfos:         file_proto_api_env_proto_enumTypes,
	}.Build()
	File_proto_api_env_proto = out.File
	file_proto_api_env_proto_rawDesc = nil
	file_proto_api_env_proto_goTypes = nil
	file_proto_api_env_proto_depIdxs = nil
}
