name: tests

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches-ignore:
      - main
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
          cache: false # use golangci cache instead
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
